# Generated by Django 4.0.10 on 2023-12-15 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_kk', models.CharField(max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Города',
                'verbose_name_plural': 'Города',
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_kk', models.CharField(max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Компании',
                'verbose_name_plural': 'Компании',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('author_pic', models.ImageField(blank=True, help_text='Extensions: .jpg .jpeg, .png,', null=True, upload_to='jobs', verbose_name='Фото')),
                ('body_text', models.TextField(verbose_name='Текст обзора')),
                ('body_text_ru', models.TextField(null=True, verbose_name='Текст обзора')),
                ('body_text_kk', models.TextField(null=True, verbose_name='Текст обзора')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
                'db_table': 'socials',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, unique=True, verbose_name='Название')),
                ('name_kk', models.CharField(max_length=255, null=True, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='ignore this field', max_length=255, unique=True, verbose_name='URL')),
                ('model_pic', models.ImageField(blank=True, help_text='Extensions: .jpg .jpeg, .png,', null=True, upload_to='jobs', verbose_name='Фото')),
                ('salary', models.DecimalField(decimal_places=2, help_text='Numeric field (1200, 1200.5)', max_digits=15, verbose_name='Зарплата')),
                ('responsibility_text', models.TextField(blank=True, null=True, verbose_name='Обязанность')),
                ('responsibility_text_ru', models.TextField(blank=True, null=True, verbose_name='Обязанность')),
                ('responsibility_text_kk', models.TextField(blank=True, null=True, verbose_name='Обязанность')),
                ('requirement_text', models.TextField(blank=True, null=True, verbose_name='Требования')),
                ('requirement_text_ru', models.TextField(blank=True, null=True, verbose_name='Требования')),
                ('requirement_text_kk', models.TextField(blank=True, null=True, verbose_name='Требования')),
                ('schedule', models.TextField(blank=True, null=True, verbose_name='Расписание')),
                ('schedule_ru', models.TextField(blank=True, null=True, verbose_name='Расписание')),
                ('schedule_kk', models.TextField(blank=True, null=True, verbose_name='Расписание')),
                ('working_condition_text', models.TextField(blank=True, null=True, verbose_name='Рабочие условия')),
                ('working_condition_text_ru', models.TextField(blank=True, null=True, verbose_name='Рабочие условия')),
                ('working_condition_text_kk', models.TextField(blank=True, null=True, verbose_name='Рабочие условия')),
                ('accommodation', models.TextField(blank=True, null=True, verbose_name='Проживание')),
                ('accommodation_ru', models.TextField(blank=True, null=True, verbose_name='Проживание')),
                ('accommodation_kk', models.TextField(blank=True, null=True, verbose_name='Проживание')),
                ('nutrition', models.TextField(blank=True, null=True, verbose_name='Питание')),
                ('nutrition_ru', models.TextField(blank=True, null=True, verbose_name='Питание')),
                ('nutrition_kk', models.TextField(blank=True, null=True, verbose_name='Питание')),
                ('additional_text', models.TextField(blank=True, null=True, verbose_name='Дополнительный текст')),
                ('additional_text_ru', models.TextField(blank=True, null=True, verbose_name='Дополнительный текст')),
                ('additional_text_kk', models.TextField(blank=True, null=True, verbose_name='Дополнительный текст')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время публикации')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='published', help_text='Select "Published" to publish', max_length=20, verbose_name='Статус')),
                ('city', models.ForeignKey(help_text='Choose a city from the list', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='job.city', verbose_name='Город')),
                ('company', models.ForeignKey(help_text='Choose a company from the list', on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='job.company', verbose_name='Компания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Вакансии',
                'verbose_name_plural': 'Вакансии',
                'db_table': 'vacancy',
                'ordering': ['-publish'],
            },
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['-publish', 'name', 'responsibility_text'], name='vacancy_publish_0cc94f_idx'),
        ),
    ]
