# Generated by Django 4.0.10 on 2023-11-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name',
            field=models.CharField(default='Варшава', max_length=255, verbose_name='Название города'),
            preserve_default=False,
        ),
    ]
