# Generated by Django 4.0.10 on 2023-11-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
