# Generated by Django 4.0.10 on 2023-11-15 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_vacancy_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Города', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компаний', 'verbose_name_plural': 'Компаний'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-publish'], 'verbose_name': 'Вакансии', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
