# Generated by Django 4.0.10 on 2023-11-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_vacancy_user_alter_vacancy_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='model_pic',
            field=models.ImageField(blank=True, null=True, upload_to='jobs'),
        ),
    ]
