# Generated by Django 4.0.10 on 2023-11-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_remove_vacancy_body_vacancy_accommodation_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vacancy',
            name='vacancy_publish_4aa261_idx',
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['-publish', 'name', 'responsibility_text'], name='vacancy_publish_0cc94f_idx'),
        ),
    ]
