# Generated by Django 4.0.10 on 2023-11-27 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0009_remove_vacancy_vacancy_publish_4aa261_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Cities', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Companies', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Reviews', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-publish'], 'verbose_name': 'Vacancies', 'verbose_name_plural': 'Vacancies'},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='accommodation_en',
            field=models.TextField(blank=True, null=True, verbose_name='Accommodation'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='accommodation_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Accommodation'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='accommodation_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Accommodation'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='additional_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Additional text'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='additional_text_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Additional text'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='additional_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Additional text'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='name_kz',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='nutrition_en',
            field=models.TextField(blank=True, null=True, verbose_name='Nutrition'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='nutrition_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Nutrition'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='nutrition_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Nutrition'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirement_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Requirements'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirement_text_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Requirements'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirement_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Requirements'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='responsibility_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Responsibility'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='responsibility_text_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Responsibility'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='responsibility_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Responsibility'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='schedule_en',
            field=models.TextField(blank=True, null=True, verbose_name='Schedule'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='schedule_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Schedule'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='schedule_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Schedule'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='working_condition_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Working Condition'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='working_condition_text_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Working Condition'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='working_condition_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Working Condition'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='review',
            name='body_text',
            field=models.TextField(verbose_name='Text of review'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='accommodation',
            field=models.TextField(blank=True, null=True, verbose_name='Accommodation'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='additional_text',
            field=models.TextField(blank=True, null=True, verbose_name='Additional text'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='city',
            field=models.ForeignKey(help_text='Choose a city from the list', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='job.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(help_text='Choose a company from the list', on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='job.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='model_pic',
            field=models.ImageField(blank=True, help_text='Extensions: .jpg .jpeg, .png,', null=True, upload_to='jobs', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='nutrition',
            field=models.TextField(blank=True, null=True, verbose_name='Nutrition'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published Time'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirement_text',
            field=models.TextField(blank=True, null=True, verbose_name='Requirements'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='responsibility_text',
            field=models.TextField(blank=True, null=True, verbose_name='Responsibility'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.DecimalField(decimal_places=2, help_text='Numeric field (1200, 1200.5)', max_digits=15, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='schedule',
            field=models.TextField(blank=True, null=True, verbose_name='Schedule'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='slug',
            field=models.SlugField(help_text='ignore this field', max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', help_text='Select "Published" to publish', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='working_condition_text',
            field=models.TextField(blank=True, null=True, verbose_name='Working Condition'),
        ),
    ]
