<<<<<<< HEAD
# Generated by Django 4.0.10 on 2023-11-25 14:56
=======
# Generated by Django 4.0.10 on 2023-11-25 14:30
>>>>>>> 4bb87b3412963dd28b129e81f1bbbb9b2f0eab69

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0009_remove_vacancy_vacancy_publish_4aa261_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Cities', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Companies', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Reviews', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-publish'], 'verbose_name': 'Vacancies', 'verbose_name_plural': 'Vacancies'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='review',
            name='body_text',
            field=models.TextField(verbose_name='Text of review'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='accommodation',
            field=models.TextField(blank=True, null=True, verbose_name='Accommodation'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='additional_text',
            field=models.TextField(blank=True, null=True, verbose_name='Additional text'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='job.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='job.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='model_pic',
            field=models.ImageField(blank=True, null=True, upload_to='jobs', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='nutrition',
            field=models.TextField(blank=True, null=True, verbose_name='Nutrition'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published Time'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirement_text',
            field=models.TextField(blank=True, null=True, verbose_name='Requirements'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='responsibility_text',
            field=models.TextField(blank=True, null=True, verbose_name='Responsibility'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='schedule',
            field=models.TextField(blank=True, null=True, verbose_name='Schedule'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='working_condition_text',
            field=models.TextField(blank=True, null=True, verbose_name='Working Condition'),
        ),
    ]
