# Generated by Django 4.0.10 on 2023-11-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_alter_city_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='accommodation_kz',
            new_name='accommodation_kk',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='additional_text_kz',
            new_name='additional_text_kk',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='name_kz',
            new_name='name_kk',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='nutrition_kz',
            new_name='nutrition_kk',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='requirement_text_kz',
            new_name='requirement_text_kk',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='responsibility_text_kz',
            new_name='responsibility_text_kk',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='schedule_kz',
            new_name='schedule_kk',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='working_condition_text_kz',
            new_name='working_condition_text_kk',
        ),
    ]
