# Generated by Django 4.0.10 on 2023-11-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_city_name_en_city_name_kk_city_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='review',
            name='author_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='review',
            name='author_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='review',
            name='body_text_en',
            field=models.TextField(null=True, verbose_name='Text of review'),
        ),
        migrations.AddField(
            model_name='review',
            name='body_text_kk',
            field=models.TextField(null=True, verbose_name='Text of review'),
        ),
        migrations.AddField(
            model_name='review',
            name='body_text_ru',
            field=models.TextField(null=True, verbose_name='Text of review'),
        ),
    ]
