# Generated by Django 4.0.10 on 2023-12-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_review_author_en_review_author_kk_review_author_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author_en',
        ),
        migrations.RemoveField(
            model_name='review',
            name='author_kk',
        ),
        migrations.RemoveField(
            model_name='review',
            name='author_ru',
        ),
        migrations.AddField(
            model_name='review',
            name='author_pic',
            field=models.ImageField(blank=True, help_text='Extensions: .jpg .jpeg, .png,', null=True, upload_to='jobs', verbose_name='Photo'),
        ),
    ]
