# Generated by Django 4.0.10 on 2023-12-14 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0014_remove_review_author_en_remove_review_author_kk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.URLField(verbose_name='URL to link')),
            ],
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Города', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компании', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзывы', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-publish'], 'verbose_name': 'Вакансии', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.RemoveField(
            model_name='city',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='company',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='review',
            name='body_text_en',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='accommodation_en',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='additional_text_en',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='nutrition_en',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='requirement_text_en',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='responsibility_text_en',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='schedule_en',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='working_condition_text_en',
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author_pic',
            field=models.ImageField(blank=True, help_text='Extensions: .jpg .jpeg, .png,', null=True, upload_to='jobs', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='review',
            name='body_text',
            field=models.TextField(verbose_name='Текст обзора'),
        ),
        migrations.AlterField(
            model_name='review',
            name='body_text_kk',
            field=models.TextField(null=True, verbose_name='Текст обзора'),
        ),
        migrations.AlterField(
            model_name='review',
            name='body_text_ru',
            field=models.TextField(null=True, verbose_name='Текст обзора'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='accommodation',
            field=models.TextField(blank=True, null=True, verbose_name='Проживание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='accommodation_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Проживание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='accommodation_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Проживание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='additional_text',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительный текст'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='additional_text_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительный текст'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='additional_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительный текст'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='city',
            field=models.ForeignKey(help_text='Choose a city from the list', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='job.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(help_text='Choose a company from the list', on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='job.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='model_pic',
            field=models.ImageField(blank=True, help_text='Extensions: .jpg .jpeg, .png,', null=True, upload_to='jobs', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='nutrition',
            field=models.TextField(blank=True, null=True, verbose_name='Питание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='nutrition_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Питание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='nutrition_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Питание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirement_text',
            field=models.TextField(blank=True, null=True, verbose_name='Требования'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirement_text_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Требования'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirement_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Требования'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='responsibility_text',
            field=models.TextField(blank=True, null=True, verbose_name='Обязанность'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='responsibility_text_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Обязанность'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='responsibility_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Обязанность'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.DecimalField(decimal_places=2, help_text='Numeric field (1200, 1200.5)', max_digits=15, verbose_name='Зарплата'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='schedule',
            field=models.TextField(blank=True, null=True, verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='schedule_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='schedule_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='published', help_text='Select "Published" to publish', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='working_condition_text',
            field=models.TextField(blank=True, null=True, verbose_name='Рабочие условия'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='working_condition_text_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Рабочие условия'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='working_condition_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Рабочие условия'),
        ),
    ]
