# Generated by Django 4.0.10 on 2023-12-14 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_socialmedia_alter_city_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Social_Media', 'verbose_name_plural': 'Social_Media'},
        ),
        migrations.AlterModelTable(
            name='socialmedia',
            table='socials',
        ),
    ]
