# Generated by Django 4.0.10 on 2023-12-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_alter_socialmedia_options_alter_socialmedia_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Social Media', 'verbose_name_plural': 'Social Media'},
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
